apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: welcome-hooks-2
  namespace: argocd
  labels:
    app: test
spec:
  generators:
    - list:
        elements:
          - cluster: engineering-dev-2
            url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{cluster}}-hooks'
    spec:
      destination:
        namespace: argocd
        server: '{{url}}'
      project: default
      source:
        path: apps/welcome-php/overlays/hooks
        repoURL: 'https://github.com/taiseerhussein/openshift-gitops-examples.git'
        targetRevision: 2.0.3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
