apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-hooks
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/welcome-php/overlays/hooks
    repoURL: https://github.com/taiseerhussein/openshift-gitops-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false

